# Generated by Django 5.0.4 on 2024-05-06 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_type', models.CharField(max_length=50)),
                ('origin_currency', models.CharField(max_length=10)),
                ('exchange_currency', models.CharField(max_length=10)),
                ('buy_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('sell_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
